<div class="container">
  <div class="row">
	<?php if(!empty($this->data)):
		  $pos=1;
    ?>
	<?php  foreach($this->data as $image): ?>
		   <? if(empty($image['description'])) $image['description'] = "N/A" ; ?>
	       <div class="span3" >
	       <div class="well imgWrap">
	       	<input name="id" type="hidden" value= "<?= $image['id'] ?>" />
	       	<?php if(!$this->enableFav):?>
	           <a class="btn btn-mini add" href="#" ><i class="icon-plus-sign"></i> Add to Favorites</a>
	        <?php else: ?>
	           <a class="btn btn-mini delete" href="#" ><i class="icon-trash"></i> Remove from Favorites</a>
	        <?php endif; ?>

		     <div class="thumbnail" >
				<img src="<?= $image['link']; ?>" data-src="holder.js/280x200" />
				<br/>
			   <?php if(!$this->enableFav):?>
				<h5> Title: <?= $image['title']; ?></h5>
				<p>Description: <?= $image['description']; ?></p>
			   <?php else: ?>
				<textarea name="title" rows="1" placeholder="<?= $image['title']; ?>" ></textarea>
				<textarea name="description" rows="1" placeholder="<?= $image['description']; ?>" ></textarea>
			   <?php endif; ?>
				<a class="btn btn-primary edit" href="#" <?php if(!$this->enableFav){ echo 'style="display: none;"'; } ?> >Update</a>
				<span class="info btn btn-info" style="display:none" ></span>
			</div>
			</div>
	       	</div>
	   <?php if(($pos%4)==0): ?>
		</div>
		<?php if($pos!=20): ?><div class="row"><?php endif;?>
		<?php endif;?>

	<?php $pos++; endforeach;?>
	<?php else:?>
		<div class="span" ><h5> No images added to this section</h5></div>
	<?php endif;?>
  </div>
</div> <!-- /container -->