<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Imact, Stumble upon and catalog your favorite Imgur pics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?=self::$basePath ?>assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="<?=self::$basePath ?>assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?=self::$basePath ?>assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?=self::$basePath ?>assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?=self::$basePath ?>assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="<?=self::$basePath ?>assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="<?=self::$basePath ?>assets/ico/favicon.png">
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="./">Imact</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="<?=self::$basePath ?>collage/random/">Collage</a></li>
              <li><a href="<?=self::$basePath ?>favorite/read/">Favorites</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <?php $this->content(); ?>
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?=self::$basePath ?>assets/js/jquery-1.9.0.js"></script>
    <script src="<?=self::$basePath ?>assets/js/bootstrap.js"></script>
    <script src="<?=self::$basePath ?>assets/js/script.js"></script>
  </body>
</html>